spring:
  application:
    name: carrito-compras-service
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8180/realms/microservices-ecosystem
          jwk-set-uri: http://localhost:8180/realms/microservices-ecosystem/protocol/openid-connect/certs
  datasource:
    url: jdbc:h2:mem:payment
    driver-class-name: org.h2.Driver
    username: admin
    password: admin123
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
  h2:
    console:
      enabled: true
  # Configuración de Kafka
  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost:9092
          auto-create-topics: true
          configuration:
            "[key.serializer]": org.apache.kafka.common.serialization.StringSerializer
            "[value.serializer]": org.springframework.kafka.support.serializer.JsonSerializer
            "[key.deserializer]": org.apache.kafka.common.serialization.StringDeserializer
            "[value.deserializer]": org.springframework.kafka.support.serializer.JsonDeserializer
            "[spring.json.trusted.packages]": "*"
      bindings:
        serviceRequest-out-0:
          destination: service-request-topic
          content-type: application/json

server:
    port: 8084

management:
  endpoints:
    web:
      exposure:
        # Exposes monitoring for every endpoint
        # through /actuator/metrics
        include: "*"

  endpoint:
    health:
      # Adds an endpoint to monitor service health
      # /actuator/health
      show-details: always

  info:
    env:
      enabled: true

# Configuración para simulación de pagos
payment:
  simulation:
    enabled: true
    success-rate: 0.85
    min-delay: 2000
    max-delay: 5000

